language: node_js
node_js:
  - 'stable'
  - '0.12'
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install
  - gulp --cordova "prepare"
script: gulp build
